### ISSUE TITLE
Root Project issue

### ISSUE THREAD

**Issue by rondefreitas** [BoolBySigma/UpdateNetCorePackageInfo#1]
Using .NET Core projects and Visual Studio 2017 in VSTS on visualStudio online.  Every project I try to use this with (even with the default settings) results in the following:

File 'C:/agent/_work/52/s/src/#########################.csproj' does not contain a root Project. Make sure it is a project file.

**Comment by rondefreitas** [comment]
looks like this may have been related to a bad migrate. Will reopen after investigation if required.

**Comment by maxpower720** [comment]
I'm seeing the same thing - also on a migrated project.

**Comment by naishx** [comment]
I solved the problem by changing the encoding. Somehow visual studio saves the .csproj always with encoding UTF-8-BOM if you change the encoding back (with notepad++ for example) to UTF-8 the error disappears.
